-- 1. Create the polls table
CREATE TABLE polls (
  id TEXT PRIMARY KEY,
  question TEXT NOT NULL,
  options TEXT[] NOT NULL,
  votes INTEGER[] NOT NULL,
  status TEXT DEFAULT 'active',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  correct_option_index INTEGER
);

-- 2. Create the votes_records table
CREATE TABLE votes_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  poll_id TEXT REFERENCES polls(id) ON DELETE CASCADE,
  voter_name TEXT NOT NULL,
  voter_mobile TEXT NOT NULL,
  option_index INTEGER NOT NULL,
  voted_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS (Row Level Security) if desired, or leave open for simple API access.
-- Since we are querying from a private Node.js backend using the Service/Anon key,
-- you can bypass RLS for now or enable it depending on your security needs.
ALTER TABLE polls DISABLE ROW LEVEL SECURITY;
ALTER TABLE votes_records DISABLE ROW LEVEL SECURITY;
